spring.application.name=azhly

# Aiven.io MySQL connection string (Apna actual URL, username, password yahan lagayein)
spring.datasource.url=jdbc:mysql://YOUR_AIVEN_HOST:YOUR_PORT/YOUR_DB_NAME
spring.datasource.username=YOUR_USERNAME
spring.datasource.password=YOUR_PASSWORD

# Automatic Table Creation & SQL Logs
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Allow React Frontend to connect without CORS error
spring.mvc.cors.allowed-origins=http://localhost:5173,http://localhost:5174